# Generated by Django 2.2.17 on 2020-11-28 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCad', models.DateTimeField(auto_created=True)),
                ('codigo', models.SmallIntegerField(auto_created=True)),
                ('dataUpdate', models.DateTimeField(auto_now=True)),
                ('pais', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=3)),
                ('ddi', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCad', models.DateTimeField(auto_created=True)),
                ('codigo', models.SmallIntegerField(auto_created=True)),
                ('dataUpdate', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='PaisEstadoCidade.Paises')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCad', models.DateTimeField(auto_created=True)),
                ('codigo', models.SmallIntegerField(auto_created=True)),
                ('dataUpdate', models.DateTimeField(auto_now=True)),
                ('cidade', models.CharField(max_length=50)),
                ('ddd', models.CharField(max_length=3)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='PaisEstadoCidade.Estados')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
    ]
